# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93b5f3e3fa6efa373b4d43d7024f1bdf00e6b04ba561b6f81967d441c524e6cfcb3a1a62ba21bf5d85999e5d78716ce1b33afa78e7e2b25ade84dbc4db0618b2

test:
  secret_key_base: 2947e148ccb33667adbe124e422a18524b34a096d820cbf836e28844b054fedf947c18bd0ae662fc39433a4723f6952058f8a27dab97817aedac6de35fc8f6d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
